# Site settings
title: 林浩的博客
email: 15101538245@163.com || 976220342@qq.com
description: 林浩的博客 java爱好者
github_username:  linhao007
permalink: /:year/:month/:day/:title/
duoshuo_username: linhao007
markdown: kramdown
pygments: true 
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

# encoding:utf-8
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page:num"
